### ISSUE TITLE
【依頼：BaseballModel】バットの位置初期化

### ISSUE THREAD

**Issue by norihirosunada** [TNCT-Nakano/Unity#10]
バットを初期位置に戻すイベントを作る。
### 案①
- バットを地面に置き、水平と垂直の軸の初期化
- 自分から縦向きにバットを置き、正面の方向を決める
**予想**
- 一番安定しそう

**Comment by getpa** [comment]
**案2**

- ホログラムで初期化位置を提示
- ホログラムとバットを重ね合わせた状態でボイスコマンド入力⇨初期化

**予想**
一番MRチックでかっこいい、ユーザー的には手軽

**Comment by getpa** [comment]
i'll working in it

**Comment by getpa** [comment]
案2をBatPositionInitブランチで実装

initと発声するとバットの初期化開始
目の前のホログラムに現実のバットを重ね合わせてdoneと発声するとセンサーからの情報で動くようになる
