### ISSUE TITLE
【依頼：BaseballModel】メニュー画面

### ISSUE THREAD

**Issue by norihirosunada** [TNCT-Nakano/Unity#2]
シーン同士を繋げるメニュー画面を作る。

以下のシーンと機能へ遷移させる
・各ゲーム（野球、バドミントン、剣道、etc）
・設定画面
・ゲーム終了

**Comment by getpa** [comment]
I'll be working in

ゲーム終了っていう機能はいらないと思う、Hololensのアプリ終了はOSレベルでジェスチャーによって制御されているので

**Comment by norihirosunada** [comment]
了解、とりあえずは任せた
使いやすく作れればいいから適宜必要になれば追加していこう

**Comment by getpa** [comment]
SceneChangerブランチで対応
