### ISSUE TITLE
【依頼：BaseballModel】ストライクゾーンの可視化

### ISSUE THREAD

**Issue by norihirosunada** [TNCT-Nakano/Unity#5]
おおよそのストライクゾーンがわかるように枠を作る。

**Comment by norihirosunada** [comment]
固定された状態でストライクゾーンを設置
通過を検出してログに出される
体勢によってストライクゾーンの大きさが変わるようにしたいかも

**Comment by norihirosunada** [comment]
ホームベースとかも追加した

**Comment by getpa** [comment]
#12 から
ストライクゾーンの位置が現在自分の頭にきているので、正しい位置に初期化する必要がある

**Comment by getpa** [comment]
バッターボックスを実装する必要性が高い

バッターボックス・ホームベースは大きさが規定されており、ストライクゾーンの高低についてはルール上曖昧な部分があるため、バッターボックス・ホームベース・ストライクゾーンを一つのPrefabにし、地面に配置することで位置の初期化問題などもすべて解決と考える

**Comment by norihirosunada** [comment]
バッターボックスは製作済み
後ほどマージして反映させる
