### ISSUE TITLE
【依頼：BaseballModel】プレイヤー操作画面作成

### ISSUE THREAD

**Issue by norihirosunada** [TNCT-Nakano/Unity#7]
プレイヤーに追従するメニュー画面を作る。

参考：【HoloLens】Unityでスタートメニューみたいな追従するUIを作る
[http://kzonag.hatenablog.com/entry/2016/08/14/163736](url)

**Comment by getpa** [comment]
i'll be working in

**Comment by getpa** [comment]
prefab/MenuSample.prefabを追加して終了
