### ISSUE TITLE
【依頼：BaseballModel】BlueNinjaでバットを動かす

### ISSUE THREAD

**Issue by norihirosunada** [TNCT-Nakano/Unity#8]
## BlueNinjaとバットの動きを同期させる。

- BlueNinjaからのデータの遅延は無いとする。

### 送られてくるデータについて：
- 計測値はMPU-9250のRAWデータ
- ジャイロは、最大値2000 degree/sで1/16.4(≒0.06)degree/s単位
- 加速度は、最大16Gで1/2048(≒0.00005)G単位

**Comment by norihirosunada** [comment]
BlueCommのスタブを使ってバットが動いた

**Comment by getpa** [comment]
このIssueに関連するコード、主にBatBehaviourをBatPositionInitにて修正しました
